In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# Jupyter notebook
Permite combinar código Python (celdas Code) con texto con formato y fórmulas matemáticas en Latex (celdas Markdown). Vamos a usar frecuentemente Jupyter notebook en las clases.

Pueden utilizar Jupyter notebook offline desde Anaconda (u otros) o alguna herramienta online, como Google Colab.

Para hacer las prácticas pueden usar Jupyter notebook o cualquier otro entorno.


In [1]:
# Ejemplo de código
2 + 3 * 5

17

In [2]:
# Podemos ingresar varias instrucciones en la misma celda
a = 5
a

5

In [3]:
# Si ejecutamos varios comandos en una misma celda solo se muestra la última salida
b = 3.14
b
b * 2

6.28

In [4]:
# Podemos usar display o print para ver varias salidas
c = "hola"
display(c)
print(a)

'hola'

5


### Orden de ejecución
Para ejecutar el contenido de una celta usamos SHIFT+Enter.
Los comandos dentro de la celda se ejecutan en orden.

Si abrimos un Notebook con varias celdas con código, el contenido de esas celdas no se ejecuta hasta que lo hagamos nosotros (podemos hacerlo celda por celda o ejecutar todas automaticamente utilizando "Cell" --> "Run all".

Ejecutar la primer celda, luego la siguiente y luego nuevamente la primera y ver qué sucede.

In [7]:
print(z)

10


In [9]:
z = 10

**Consejo:** Si entregan código en Jupyter Notebook verifiquen siempre que se pueden ejecutar las celdas en orden de arriba hacia abajo.

### Funciones matemáticas

In [10]:
a = 5
b = 3.14
a * b # Producto

15.700000000000001

In [11]:
print(a**3) # Potencia

125


In [12]:
print(b % 2) # ¿Qué hace?

1.1400000000000001


In [14]:
help('%')

Operator precedence
*******************

The following table summarizes the operator precedence in Python, from
highest precedence (most binding) to lowest precedence (least
binding).  Operators in the same box have the same precedence.  Unless
the syntax is explicitly given, operators are binary.  Operators in
the same box group left to right (except for exponentiation, which
groups from right to left).

Note that comparisons, membership tests, and identity tests, all have
the same precedence and have a left-to-right chaining feature as
described in the Comparisons section.

+-------------------------------------------------+---------------------------------------+
| Operator                                        | Description                           |
|=================================================|=======================================|
| "(expressions...)",  "[expressions...]", "{key: | Binding or parenthesized expression,  |
| value...}", "{expressions...}"                 

In [15]:
### Tipos de datos
type(a)

int

In [16]:
type(b)

float

In [17]:
### Las funciones de Python pueden llamarse con variables de distinto tipo, y se comportan distinto según el tipo de dato
d = 5.0
type(d)

float

In [18]:
a**100

7888609052210118054117285652827862296732064351090230047702789306640625

In [19]:
d**100

7.888609052210118e+69

In [21]:
b**100

4.931338416605635e+49

In [20]:
type(c)

str

In [22]:
c*2

'holahola'

### Variables booleanas y funciones lógicas
En Python podemos usar variables booleanas True y False, y operadores lógicos: == (igualdad), or, and, ~ (not).

In [25]:
a = True
b = False
print(a == b)
print(a or b)
print(a and b)
print(a == (not b))

False
True
False
True


El operador de igualdad aplicado a variables numércias compara solo el valor, no el tipo de dato.

In [26]:
x1 = 5.0
x2 = 7.0
x3 = 12.0
n1 = 5
print(x1+x2 == x3)
print(x1 == 5)
print(x1 == n1)

True
True
True


In [28]:
type(x1) == type(n1)

False

In [29]:
type(x1) == type(x2)

True

### Listas
Las listas permiten guardar valores de distintos tipos en forma ordenada y acceder a
los distintos elementos por su índice, comenzando desde 0.

In [30]:
s = [1, 2, 3.0, "hola", 7 + 3]
s

[1, 2, 3.0, 'hola', 10]

In [31]:
print(s[0])
print(s[1])
print(s[-1])

1
2
10


Podemos indicar también un rango de elementos de la lista.

In [32]:
s[1:3] # ¿Qué nos devuelve? ¿Por qué?

[2, 3.0]

# Numpy

Para trabajar en Python con vectores (y en general para todo tipo de operaciones
matemáticas) vamos a usar el paquete `numpy` . Para eso importamos primero la biblioteca `numpy`
y definimos vectores con el comando `np.array`. 

**Vectores.** Los vectores (o arrays) de numpy son similares a las listas, pero todos los elementos son del mismo tipo (enteros, floats, ...)

Ejecutar el siguiente código y observar los resultados.

In [33]:
import numpy as np
v = np.array([1,2,3])
w = np.array([1.2, 7, np.pi])
print(v)
print(w)
print(v + w)

[1 2 3]
[1.2        7.         3.14159265]
[2.2        9.         6.14159265]


In [34]:
# El tipo de dato de un array de numpy es ndarray
print(type(v))
print(type(w))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [35]:
# Si queremos saber el tipo de dato de los elementos del array, usamos dtype
print(v.dtype)
print(w.dtype)

int64
float64


(dtype es un método del objeto ndarray, por eso usamos la escritura v.dtype y no dtype(v))

### La magia de Numpy. 
La biblioteca Numpy reproduce muchas funcionalidades de Matlab.
La mayoría de las operaciones con vectores de Numpy se hacen coordenada a coordenada. Esto permite en muchos casos evitar usar ciclos o ciclos anidados y realizarlos con un solo comando.

Ejecutar los siguientes comandos e interpretar los resultados.

In [36]:
v = np.array([1,2,np.e,7])
w = np.array([1.2, np.pi, 4, 5])
print("v = ", v)
print("w = ", w)
print("v + w = ", v + w)
print ("v**2 = ", v**2)
print ("v%2 = ", v%2)
print ("v > 3?", v > 3)
print ("w < 3.5?", w < 3.5)


v =  [1.         2.         2.71828183 7.        ]
w =  [1.2        3.14159265 4.         5.        ]
v + w =  [ 2.2         5.14159265  6.71828183 12.        ]
v**2 =  [ 1.         4.         7.3890561 49.       ]
v%2 =  [1.         0.         0.71828183 1.        ]
v > 3? [False False False  True]
w < 3.5? [ True  True False False]


Algunas funciones de numpy pueden usarse también como métodos

In [37]:
print(v.sum())
print(np.sum(v))

12.718281828459045
12.718281828459045


Las operaciones lógicas or y and no se pueden aplicar a vectores. Debemos usar los símbolos |
(or) y & (and).

In [39]:
print((v > 3) | (w < 3.5))
print((v > 3) & (w < 3.5))

[ True  True False  True]
[False False False False]


Si queremos quedarnos con sólo algunos elementos de un vector, tenemos varias formas de hacerlo.

In [40]:
v = np.array([1, 2, np.e, 7, 5])
v[0], v[1], v[-1]  # funcionara ‘v[-2]‘?

(1.0, 2.0, 5.0)

In [41]:
v[[0, 3]]

array([1., 7.])

In [42]:
# Ojo, no podemos hacer lo mismo con listas
s = [1, 2, 3.0, "hola", 7 + 3]
s[[0,3]]

TypeError: list indices must be integers or slices, not list

In [43]:
# También podemos usar rangos
v[0:3]

array([1.        , 2.        , 2.71828183])

In [44]:
v[0:1]

array([1.])

Y podemos seleccionar los elementos que cumplan alguna propiedad.

In [45]:
v = np.array([1, 2, np.e, 7, 5])
w = np.array([1, 0, 2, 5, 0])
print(v)
v[v > 2]

[1.         2.         2.71828183 7.         5.        ]


array([2.71828183, 7.        , 5.        ])

In [46]:
v[w != 0]

array([1.        , 2.71828183, 7.        ])

**Matrices.** Las matrices se definen en numpy como arrays de filas. Las operaciones usuales
se realizan coordenada a coordenada al igual que con vectores. Verificar los resultados de los
siguientes comandos.

In [48]:
A = np.array([[3, 2, 2], [-1, 0, 1], [-2, 2, 4]])
B = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
C = np.array([[0, 1, -1], [5, -2, 1]])
A + B

array([[ 4,  2,  2],
       [-1,  1,  1],
       [-2,  2,  5]])

In [49]:
A * B

array([[3, 0, 0],
       [0, 0, 0],
       [0, 0, 4]])

In [50]:
C**2 

array([[ 0,  1,  1],
       [25,  4,  1]])

El producto usual de matrices se realiza con el comando @ . 

A.T es la transpuesta de A. 

Verificar los resultados de los siguientes comandos.

In [51]:
A @ B

array([[ 3,  2,  2],
       [-1,  0,  1],
       [-2,  2,  4]])

In [52]:
B @ C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [53]:
B.shape, C.shape

((3, 3), (2, 3))

In [54]:
B @ C.T

array([[ 0,  5],
       [ 1, -2],
       [-1,  1]])

## Funciones

Las funciones son bloques de código organizado que se usan para realizar tares específicas.

Reciben un input (un número o una variable, por ejemplo) y devuelven un output. Los inputs van
entre paréntesis y separados por una coma, si hay más de uno. 

Muchas funciones están disponibles en la biblioteca estándar de Python, otras estás agrupadas en distintas bibliotecas, como numpy que agrupa una gran cantidad de funciones matemáticas. 

El objetivo de estos ejercicios es familiarizarse con varias funciones básicas de Python.

Ejecutar estas operaciones en la consola para entender qué hacen las funciones de numpy.

In [55]:
a = np.sqrt(2)
a

1.4142135623730951

In [56]:
np.round(a)

1.0

In [57]:
np.round(a, 2)

1.41

In [58]:
# Para las funciones de numpy, podems ver información con np.info
np.info(np.round)

 round_(a, decimals=0, out=None)

Round an array to the given number of decimals.

See Also
--------
around : equivalent function; see for details.


In [59]:
np.info(np.ceil)

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
``i >= x``.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``

In [60]:
np.ceil(np.pi)

4.0

Muchas funciones de numpy se pueden aplicar también en arrays.

In [61]:
v = np.array([a, a**2, a**3, a**(.5)])
v

array([1.41421356, 2.        , 2.82842712, 1.18920712])

In [62]:
np.floor(v)

array([1., 2., 2., 1.])

Explorar las funciones np.max() , np.min() , np.sum() , np.mean() y np.sort() aplicadas al vector
v del ejercicio anterior. ¿Qué hace cada una?

**Ejercicio.**
Utilizando solo las operaciones y funciones vistas en los ejercicios anteriores, escribir un código
de una sola línea para la función matemática:

$$\langle v, w\rangle = v_1 \cdot w_1 + v_2 \cdot w_2 + \dots + v_n \cdot w_n = \sum_{i=1}^n v_i \cdot w_i$$

En Python podemos definir nuestras propias funciones utilizando `def`. 

¿Qué hace la siguiente función? 

¿Qué resultados esperan al aplicar la función a los vectores $v_0$ y $v_1$?

In [63]:
v = np.array([1,0,0,2])
w = np.array([1,2,3,4])
np.sum(v*w)

9

In [65]:
def todosPositivos(v):
    return np.all(v > 0)

v0 = np.array([3, 4])
v1 = np.array([3, 5, -1, 1])

In [66]:
todosPositivos(v0)

True

In [67]:
todosPositivos(v1)

False

**Ejercicio.** Definir una función que calcule la norma-2 de un vector y verificarla en los vectores $v_0$ y $v_1$ del ejercicio anterior.

## Azar y simulaciones

Reproducir estos usos de la función np.random.choice() e interpretar qué hace.

In [68]:
x = np.array(["cara", "ceca"])
np.random.choice(x, size=10)

array(['ceca', 'ceca', 'cara', 'ceca', 'ceca', 'cara', 'cara', 'cara',
       'cara', 'ceca'], dtype='<U4')

In [69]:
y = np.array([1,2,3,4,5,6])
np.random.choice(y, size=10)

array([3, 3, 4, 2, 1, 2, 5, 3, 1, 5])

In [70]:
np.random.choice(y, size=4, replace=False)

array([2, 6, 5, 1])

In [71]:
# Funcionará?
np.random.choice(y, size=10, replace=False)

ValueError: Cannot take a larger sample than population when 'replace=False'

**Ley de los grandes números.** Esta ley asegura que si tiramos $n$ veces una moneda, el promedio de veces que sale cara tiende a $1/2$ cuando $n$ tiende a infinito.

Simular 10 lanzamientos de una moneda y calcular el promedio de veces que sale cara. Repetir para $n = 1000$ y $n = 100.000$.

In [82]:
n = 10
x = np.array(["cara", "ceca"])
s = np.random.choice(x, size=n)
print(s)
s == "cara"
np.sum(s == "cara")/n

['ceca' 'ceca' 'cara' 'cara' 'ceca' 'cara' 'cara' 'ceca' 'ceca' 'ceca']


0.4

In [ ]:
**Ejercicio.** Se tira $n$ veces una moneda. Intentar predecir, si existen, los siguientes límites cuando $n$ tiene a infinito y verificar la intuición mediante simulaciones.

1. La cantidad de caras dividido por la cantidad de cecas.
2. La cantidad de caras menos la cantidad de cecas
3. La cantidad de caras menos la cantidad de cecas, divido por la cantidad total de tiradas.
4. Considerando las veces que salieron tres caras seguidas, el promedio de veces que en la siguiente tirada sale nuevamente cara.


In [ ]:
suma1 = 0
for i in range(0, n-3):
    if np.all(s[i:i+4] == ["cara", "cara", "cara", "cara"]): 
        suma1 = suma1 + 1
print(suma1)

suma2 = 0 
for i in range(0, n-2):
    if np.all(s[i:i+3] == ["cara", "cara", "cara"]):
        suma2 = suma2 + 1
print(suma2)

print(suma1/suma2)

## Archivos de datos

La biblioteca Pandas nos permite trabajar fácilmente con archivos de datos.
1. Leer el archivo casos_coronavirus.csv .
2. Graficar la curva de casos por día.
3. Graficar la curva de casos acumulados.
4. Definir log_cum_casos como el logaritmo de la cantidad de casos acumulados y graficar en función de la cantidad de días transcurridos.
5. Estimar, tomando dos valores, la pendiente de la recta para los datos a partir del dia 30.
6. Graficar la recta estimada junto con los datos. ¿Consideran que es una buena estimación?

Utilicen o modifiquen el siguiente código.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("casos_coronavirus.csv") # DataFrame
df.head()  # Primeras filas del DataFrame

In [ ]:
# Información básica del DataFrame
df.info()

Vamos a ver más sobre la biblioteca `pandas` y data frames en la próxima clase. En este
ejemplo, convertimos los datos a arrays de numpy para utilizar las herramientas de los ejercicios
anteriores.

In [ ]:
# Convertimos la columna de casos nuevos a np.array
casos_diarios = df.confirmados_Nuevos.values
type(casos_diarios)

In [ ]:
casos_diarios.dtype # Es un array de enteros

In [ ]:
# Graficamos la serie de casos diarios
plt.plot(casos_diarios)

In [ ]:
# Calculamos los casos acumulados y graficamos
casos_acumulados = casos_diarios.cumsum()
plt.plot(casos_acumulados)

In [ ]:
# Tomamos logaritmos para linealizar 
y = np.log(casos_acumulados)

In [ ]:
# Graficamos
plt.plot(y)

In [ ]:
# Agregamos la recta
x_recta = ???
y_recta = ???
plt.plot(y)
plt.plot(x_recta, y_recta)
